[package]
name = "catacomb"
version = "0.1.0"
edition = "2021"
rust-version = "1.58.0"

[dependencies]
smithay = { git = "https://github.com/chrisduerr/smithay", rev = "519899e001e16f57f3ddc7b06da2c0aabb39658e", features = ["use_system_lib"] }
wayland-protocols = "0.29.1"
wayland-commons = "0.29.0"
calloop = "0.9.3"
udev = "0.6.2"
