[package]
name = "catacomb"
version = "0.1.0"
edition = "2021"

[dependencies]
smithay = { version = "0.3.0", features = ["use_system_lib"] }

# TODO: Fuck this shit honestly.
slog = "2.7.0"
slog-term = "2.8"
slog-async = "2.2"
slog-stdlog = "4.1.0"
slog-scope = "4.4.0"
