[package]
name = "catacomb"
version = "0.1.0"
edition = "2021"
rust-version = "1.56.0"

[dependencies]
smithay = { git = "https://github.com/chrisduerr/smithay", features = ["use_system_lib"] }
wayland-protocols = "0.29.1"
wayland-commons = "0.29.0"
