[package]
name = "catacomb"
version = "0.1.0"
description = "A Wayland mobile compositor"
authors = ["Christian Duerr <contact@christianduerr.com>"]
homepage = "https://github.com/chrisduerr/catacomb"
rust-version = "1.65.0"
license = "GPL-3.0"
edition = "2021"

[workspace]
members = ["catacomb_ipc"]

[dependencies.smithay]
git = "https://github.com/smithay/smithay"
default-features = false
features = [
    "use_system_lib",
    "backend_drm",
    "backend_gbm",
    "backend_libinput",
    "backend_udev",
    "backend_session_libseat",
    "renderer_gl",
]

[dependencies]
catacomb_ipc = { version = "0.1.0", path = "./catacomb_ipc", features = ["clap", "smithay"] }
serde = { version = "1.0.144", features = ["derive"] }
clap = { version = "3.2.19", features = ["derive"] }
serde_json = "1.0.85"
libc = "0.2.123"
dirs = "4.0.0"
udev = "0.6.2"
image = "0.24.5"
nix = "0.26.2"
