[package]
name = "catacomb"
version = "0.1.0"
edition = "2021"
rust-version = "1.58.0"

[dependencies]
smithay = { git = "https://github.com/chrisduerr/smithay", rev = "5129920247146d4d626f675f31603752700ef8e7", features = ["use_system_lib"] }
calloop = "0.9.3"
udev = "0.6.2"
