[package]
name = "catacomb_ipc"
version = "0.1.0"
description = "Catacomb IPC interface"
authors = ["Christian Duerr <contact@christianduerr.com>"]
homepage = "https://github.com/chrisduerr/catacomb"
rust-version = "1.65.0"
license = "GPL-3.0"
edition = "2021"

[dependencies.smithay]
git = "https://github.com/smithay/smithay"
default-features = false
features = [
    "use_system_lib",
    "backend_drm",
    "backend_gbm",
    "backend_libinput",
    "backend_udev",
    "backend_session",
    "renderer_gl",
    "renderer_multi",
    "slog-stdlog"
]
optional = true

[dependencies]
clap = { version = "3.2.19", features = ["derive"], optional = true }
serde = { version = "1.0.144", features = ["derive"] }
serde_json = "1.0.85"
dirs = "4.0.0"

[features]
default = []
clap = ["dep:clap"]
smithay = ["dep:smithay"]
